version: '3'

services:
  mongodb:
    image: mongo:latest  # Use the official MongoDB image (latest tag)
    restart: unless-stopped  # Restart the container automatically unless manually stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root  # Set username for MongoDB (optional, adjust if needed)
      - MONGO_INITDB_ROOT_PASSWORD=example  # Set password for MongoDB (optional, adjust if needed)
      - MONGO_INITDB_DATABASE=file_db
    ports:
      - 27017:27017  # Map container port 27017 (default MongoDB port) to host port 27017
    volumes:
      - mongodb-data:/data/db  # Create a named volume to persist MongoDB data

volumes:
  redis-data:  # Optional volume to persist Redis data
  mongodb-data:  # Define the named volume for persistent data
